/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOutboundIndexRouteImport } from './routes/_authenticated/outbound.index'
import { Route as AuthenticatedOutboundNewRouteImport } from './routes/_authenticated/outbound.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutboundIndexRoute =
  AuthenticatedOutboundIndexRouteImport.update({
    id: '/outbound/',
    path: '/outbound/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutboundNewRoute =
  AuthenticatedOutboundNewRouteImport.update({
    id: '/outbound/new',
    path: '/outbound/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/outbound/new': typeof AuthenticatedOutboundNewRoute
  '/outbound/': typeof AuthenticatedOutboundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/outbound/new': typeof AuthenticatedOutboundNewRoute
  '/outbound': typeof AuthenticatedOutboundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/outbound/new': typeof AuthenticatedOutboundNewRoute
  '/_authenticated/outbound/': typeof AuthenticatedOutboundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/import'
    | '/settings'
    | '/stock'
    | '/outbound/new'
    | '/outbound/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/import'
    | '/settings'
    | '/stock'
    | '/outbound/new'
    | '/outbound'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/settings'
    | '/_authenticated/stock'
    | '/_authenticated/outbound/new'
    | '/_authenticated/outbound/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outbound/': {
      id: '/_authenticated/outbound/'
      path: '/outbound'
      fullPath: '/outbound/'
      preLoaderRoute: typeof AuthenticatedOutboundIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outbound/new': {
      id: '/_authenticated/outbound/new'
      path: '/outbound/new'
      fullPath: '/outbound/new'
      preLoaderRoute: typeof AuthenticatedOutboundNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedOutboundNewRoute: typeof AuthenticatedOutboundNewRoute
  AuthenticatedOutboundIndexRoute: typeof AuthenticatedOutboundIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedOutboundNewRoute: AuthenticatedOutboundNewRoute,
  AuthenticatedOutboundIndexRoute: AuthenticatedOutboundIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
